# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  database: x
  username: x
  password: x
  encoding: unicode
  pool: 5
  timeout: 5000
