default: &default
  adapter: postgresql
  host: <%= ENV['HEROKU_PG_HOST'] %>
  port: <%= ENV['HEROKU_PG_PORT'] %>
  database: <%= ENV['HEROKU_PG_DATABASE'] %>
  username: <%= ENV['HEROKU_PG_USERNAME'] %>
  password: <%= ENV['HEROKU_PG_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
